### ISSUE TITLE
SPG as a workflow runner

### ISSUE THREAD

**Issue by edisonz0718** [storyprotocol/protocol-periphery-v1#4]
**Is your feature request related to a problem? Please describe.**
The current functions that protocols support are low level functions that do one thing at a time. However, for end users, that means sometimes it would require them to make multiple transactions to achieve one task. One example is IPA registration: In order to register an IP Asset as an artist, they have to mint a NFT first and then register it as an IP in a separate transaction. It gets even more complicated when the artist wants to attach a license term to the IPA. This can get up to 5 transactions for a simple IP registration use case.

**Describe the solution you'd like**
Story Protocol Gateway (SPG) as a periphery contract can serve as a layer on top of the core protocol to combine multiple actions together to a workflow. Some initial requirements are: 
<img width="1220" alt="Screen Shot 2024-04-17 at 4 37 18 PM" src="https://github.com/storyprotocol/protocol-periphery-v1/assets/18639326/ae057f37-16f6-4612-ba09-c72da3f8f026">

**Comment by jdubpark** [comment]
For "NFT mint," are we minting from an external contract or an NFT contract that we provide (another requirement)?

There's an issue with minting from an external contract: When we mint, we can't get the new `tokenId` because of how ERC721 is designed, so we either:
- Break it into two transactions, mint token and then the rest of actions
- Pass in expected `tokenId` from minting as a parameter (requires simulation)

**Comment by edisonz0718** [comment]
Capture our offline discussion here:
1. We don't support letting users to pass in an external nft collection. Users will have to mint themselves, get the token id and then call SPG.
2. For web2 partners, SPG can create new nft collections for them and combine mint/register for them.

**Comment by edisonz0718** [comment]
One more important workflow: 
registerAndMakeDerivative

- If users have a nft, they can pass in their nft to register and make derivative
- If users don't have a nft, they either need to create a new collection with SPG, or pass in the collection id that they created through SPG, in order to continue the workflow
